### ISSUE TITLE
ios build dl/114.5737.03 fail

### ISSUE THREAD

**Issue by IvanSiOMMP** [webrtc-sdk/webrtc-build#23]
./build.ios.sh 
++ dirname ./build.ios.sh
+ cd .
+ python3 run.py build ios --webrtc-overlap-ios-build-dir --commit ''
DEBUG:root:uname: uname_result(system='Darwin', node='yubichundeMBP.lan', release='23.3.0', version='Darwin Kernel Version 23.3.0: Wed Dec 20 21:30:44 PST 2023; root:xnu-10002.81.5~7/RELEASE_ARM64_T6000', machine='arm64')
INFO:root:OS: Darwin
DEBUG:root:mkdir -p /Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios => already exists
DEBUG:root:mkdir -p /Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release => already exists
DEBUG:root:pushd /Users/haojie/webRTC/flutter/webrtc-build/build --> /Users/haojie/webRTC/flutter/webrtc-build/build
DEBUG:root:add_path: /Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/depot_tools
Building for commit:  2ab452f5c9427dc97eb8ec2db2023cefef816e18
DEBUG:root:mkdir -p /Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/webrtc => already exists
DEBUG:root:mkdir -p /Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc => already exists
DEBUG:root:mkdir -p /Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework => already exists
DEBUG:root:+['/Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/webrtc/src/tools_webrtc/ios/build_ios_libs.sh', '-o', '/Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework', '--build_config', 'release', '--arch', 'simulator:x64', 'simulator:arm64', 'device:arm64', '--extra-gn-args', 'rtc_libvpx_build_vp9=false enable_dsyms=false use_custom_libcxx=false treat_warnings_as_errors=false rtc_use_h264=false is_component_build=false rtc_build_examples=false use_rtti=true rtc_build_tools=false rtc_enable_protobuf=false'] {}
Traceback (most recent call last):
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/webrtc/src/tools_webrtc/ios/build_ios_libs.py", line 27, in <module>
    import find_depot_tools
ModuleNotFoundError: No module named 'find_depot_tools'
DEBUG:root:popd /Users/haojie/webRTC/flutter/webrtc-build/build <-- /Users/haojie/webRTC/flutter/webrtc-build/build
Traceback (most recent call last):
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 1169, in <module>
    main()
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 1150, in main
    build_webrtc_ios(**build_webrtc_args,
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 493, in build_webrtc_ios
    cmd([
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 51, in cmd
    return subprocess.run(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/webrtc/src/tools_webrtc/ios/build_ios_libs.sh', '-o', '/Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework', '--build_config', 'release', '--arch', 'simulator:x64', 'simulator:arm64', 'device:arm64', '--extra-gn-args', 'rtc_libvpx_build_vp9=false enable_dsyms=false use_custom_libcxx=false treat_warnings_as_errors=false rtc_use_h264=false is_component_build=false rtc_build_examples=false use_rtti=true rtc_build_tools=false rtc_enable_protobuf=false']' returned non-zero exit status 1

使用build.ios.sh提示以上错误，这个如何修改可以编译通过，谢谢。

**Comment by IvanSiOMMP** [comment]
重新下载更换114.5735.10可以编译，但编译到最后提示以下错误INFO:root:gn gen /Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework/simulator/x64_libs --args=is_debug=false target_os="ios" target_cpu="x64" target_environment="simulator" ios_enable_code_signing=false ios_deployment_target="12.0" enable_ios_bitcode=false enable_stripping=true rtc_include_tests=false rtc_libvpx_build_vp9=false enable_dsyms=false use_custom_libcxx=false treat_warnings_as_errors=false rtc_use_h264=false is_component_build=false rtc_build_examples=false use_rtti=true rtc_build_tools=false rtc_enable_protobuf=false
DEBUG:root:+['gn', 'gen', '/Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework/simulator/x64_libs', '--args=is_debug=false target_os="ios" target_cpu="x64" target_environment="simulator" ios_enable_code_signing=false ios_deployment_target="12.0" enable_ios_bitcode=false enable_stripping=true rtc_include_tests=false rtc_libvpx_build_vp9=false enable_dsyms=false use_custom_libcxx=false treat_warnings_as_errors=false rtc_use_h264=false is_component_build=false rtc_build_examples=false use_rtti=true rtc_build_tools=false rtc_enable_protobuf=false'] {}
WARNING at the command-line "--args":1:158: Build argument has no effect.
is_debug=false target_os="ios" target_cpu="x64" target_environment="simulator" ios_enable_code_signing=false ios_deployment_target="12.0" enable_ios_bitcode=false enable_stripping=true rtc_include_tests=false rtc_libvpx_build_vp9=false enable_dsyms=false use_custom_libcxx=false treat_warnings_as_errors=false rtc_use_h264=false is_component_build=false rtc_build_examples=false use_rtti=true rtc_build_tools=false rtc_enable_protobuf=false
                                                                                                                                                             ^----
The variable "enable_ios_bitcode" was set as a build argument
but never appeared in a declare_args() block in any buildfile.

To view all possible args, run "gn args --list <out_dir>"

The build continued as if that argument was unspecified.

Done. Made 1386 targets from 250 files in 613ms
DEBUG:root:popd /Users/haojie/webRTC/flutter/webrtc-build/build <-- /Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/webrtc/src
DEBUG:root:+['ninja', '-C', '/Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework/simulator/x64_libs', ':default', 'api/audio_codecs:builtin_audio_decoder_factory', 'api/task_queue:default_task_queue_factory', 'sdk:native_api', 'sdk:default_codec_factory_objc', 'pc:peerconnection', 'sdk:videocapture_objc', 'sdk:framework_objc'] {}
depot_tools/ninja.py: Could not find Ninja in the third_party of the current project, nor in your PATH.
Please take one of the following actions to install Ninja:
- If your project has DEPS, add a CIPD Ninja dependency to DEPS.
- Otherwise, add Ninja to your PATH *after* depot_tools.
DEBUG:root:popd /Users/haojie/webRTC/flutter/webrtc-build/build <-- /Users/haojie/webRTC/flutter/webrtc-build/build
Traceback (most recent call last):
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 1178, in <module>
    main()
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 1159, in main
    build_webrtc_ios(**build_webrtc_args,
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 546, in build_webrtc_ios
    cmd(['ninja', '-C', work_dir, *get_build_targets('ios')])
  File "/Users/haojie/webRTC/flutter/webrtc-build/build/run.py", line 51, in cmd
    return subprocess.run(args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/haojie/webRTC/flutter/webrtc-build/build/_source/ios/depot_tools/ninja', '-C', '/Users/haojie/webRTC/flutter/webrtc-build/build/_build/ios/release/webrtc/framework/simulator/x64_libs', ':default', 'api/audio_codecs:builtin_audio_decoder_factory', 'api/task_queue:default_task_queue_factory', 'sdk:native_api', 'sdk:default_codec_factory_objc', 'pc:peerconnection', 'sdk:videocapture_objc', 'sdk:framework_objc']' returned non-zero exit status 1.
